name: supercerca
description: Final project for an app development course.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^2.1.0
  badges: ^1.1.1
  carousel_slider: ^2.1.0
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.4+2
  cloud_functions: ^0.5.0
  email_validator: ^1.0.0
  firebase_auth: ^0.16.0
  firebase_messaging: ^6.0.13
  firebase_ml_vision: ^0.9.4
  flare_dart: ^2.3.4
  flare_flutter: ^2.0.2
  flutter_credit_card: ^0.1.3
  flutter_native_splash: ^0.1.9
  flutter_spinkit: ^4.1.2+1
  flutter_svg: ^0.17.4
  google_maps_flutter: ^0.5.27+1
  image_picker: ^0.6.7
  location_permissions: ^2.0.5
  permission_handler: ^5.0.0+hotfix.5
  provider: ^4.0.4
  shared_preferences: ^0.5.7+3
  stripe_payment: ^1.0.7
  shimmer: ^1.0.0
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "0096FF"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg_images/
    - assets/students/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800
