name: supercerca
description: Final project for an app development course.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^2.1.0
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.4+2
  email_validator: ^1.0.0
  firebase_auth: ^0.16.0
  firebase_messaging: ^6.0.13
  flare_dart: ^2.3.4
  flare_flutter: ^2.0.2
  flutter_native_splash: ^0.1.9
  flutter_spinkit: ^4.1.2+1
  flutter_svg: ^0.17.4
  google_maps_flutter: ^0.5.27+1
  provider: ^4.0.4
  rxdart: ^0.22.0
  shared_preferences: ^0.5.6+3
  titled_navigation_bar: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "0096FF"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800
